name: Build

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Runner'
        required: true
        type: string
        default: 'ubuntu-latest'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      
      - name: Update 
        run: |
          cd vanadium
          git fetch --tags
          git checkout $(git tag | sort -V | tail -n1)
          cd ..
          git add vanadium
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --staged --quiet; then
            git commit -am "update"
            git push
          fi

      - name: Set ENV
        run: | 
          chmod +x *.sh
          echo "unix_time=$(date +%s)" >> $GITHUB_ENV
    
      - name: Build
        env:
            DEBIAN_FRONTEND: noninteractive
            LOCAL_TEST_JKS: ${{ secrets.LOCAL_TEST_JKS }}
            STORE_TEST_JKS: ${{ secrets.STORE_TEST_JKS }}
        run: |
          ./build.sh

      - name: Set
        run: |
          export VERSION=$(find chromium/src/out/release -name '*arm64-v8a.apk' | sed 's/.*\///;s/\-arm64-v8a.apk$//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          mv $(find chromium/src/out/release -name '*arm64-v8a.apk') $VERSION-${{ env.unix_time }}-arm64-v8a.apk

      - name: Upload Build Outputs
        uses: actions/upload-artifact@v4
        with:
          name: out-${{matrix.arch}}
          path: |
            ${{ env.VERSION }}-${{ env.unix_time }}-arm64-v8a.apk
